//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BackendResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackendResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS_i18n.BackendResources", typeof(BackendResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow comments.
        /// </summary>
        public static string AllowComments {
            get {
                return ResourceManager.GetString("AllowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Heading.
        /// </summary>
        public static string ArticleHeading {
            get {
                return ResourceManager.GetString("ArticleHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string ArticleIntro {
            get {
                return ResourceManager.GetString("ArticleIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Site!.
        /// </summary>
        public static string ConfigureMenu {
            get {
                return ResourceManager.GetString("ConfigureMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Header.
        /// </summary>
        public static string ContainerHeading {
            get {
                return ResourceManager.GetString("ContainerHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeletePage {
            get {
                return ResourceManager.GetString("DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your document was successfully saved!.
        /// </summary>
        public static string DocumentSaved {
            get {
                return ResourceManager.GetString("DocumentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Publish.
        /// </summary>
        public static string EndPublish {
            get {
                return ResourceManager.GetString("EndPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by type.
        /// </summary>
        public static string FileManagerFilterByExtension {
            get {
                return ResourceManager.GetString("FileManagerFilterByExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by file name.
        /// </summary>
        public static string FileManagerFilterByFreeText {
            get {
                return ResourceManager.GetString("FileManagerFilterByFreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Files.
        /// </summary>
        public static string FilesMenu {
            get {
                return ResourceManager.GetString("FilesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Serie.
        /// </summary>
        public static string ImageCarousel {
            get {
                return ResourceManager.GetString("ImageCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What now ?.
        /// </summary>
        public static string LeftMenuWelcome {
            get {
                return ResourceManager.GetString("LeftMenuWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing a page would be a good start, or maybe define a new document type....
        /// </summary>
        public static string LeftMenuWelcomeText {
            get {
                return ResourceManager.GetString("LeftMenuWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Types.
        /// </summary>
        public static string MenuConfigPageTypes {
            get {
                return ResourceManager.GetString("MenuConfigPageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string MenuConfigure {
            get {
                return ResourceManager.GetString("MenuConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MenuDashBoard {
            get {
                return ResourceManager.GetString("MenuDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string MenuFiles {
            get {
                return ResourceManager.GetString("MenuFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Files.
        /// </summary>
        public static string MenuMyFiles {
            get {
                return ResourceManager.GetString("MenuMyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string MenuPublishNew {
            get {
                return ResourceManager.GetString("MenuPublishNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string MenuSecurity {
            get {
                return ResourceManager.GetString("MenuSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string MenuSecurityRoles {
            get {
                return ResourceManager.GetString("MenuSecurityRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MenuSecurityUsers {
            get {
                return ResourceManager.GetString("MenuSecurityUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string MenuUploadFiles {
            get {
                return ResourceManager.GetString("MenuUploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no revisions saved for this document yet!.
        /// </summary>
        public static string NoRevisions {
            get {
                return ResourceManager.GetString("NoRevisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to save this document before you can add files / images..
        /// </summary>
        public static string NoUpload {
            get {
                return ResourceManager.GetString("NoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Content.
        /// </summary>
        public static string PageDefaultEditor {
            get {
                return ResourceManager.GetString("PageDefaultEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string PageID {
            get {
                return ResourceManager.GetString("PageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PageStatus {
            get {
                return ResourceManager.GetString("PageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish New!.
        /// </summary>
        public static string PublishNew {
            get {
                return ResourceManager.GetString("PublishNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide this.
        /// </summary>
        public static string RevisionHide {
            get {
                return ResourceManager.GetString("RevisionHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string RevisionLastMod {
            get {
                return ResourceManager.GetString("RevisionLastMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string RevisionSize {
            get {
                return ResourceManager.GetString("RevisionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RevisionStatus {
            get {
                return ResourceManager.GetString("RevisionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this revision.
        /// </summary>
        public static string RevisionUseThis {
            get {
                return ResourceManager.GetString("RevisionUseThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Revision.
        /// </summary>
        public static string RevisionViewThis {
            get {
                return ResourceManager.GetString("RevisionViewThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Draft.
        /// </summary>
        public static string SaveDraftPage {
            get {
                return ResourceManager.GetString("SaveDraftPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SavePage {
            get {
                return ResourceManager.GetString("SavePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Publish.
        /// </summary>
        public static string SavePublishPage {
            get {
                return ResourceManager.GetString("SavePublishPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/Off.
        /// </summary>
        public static string SelectedOrNot {
            get {
                return ResourceManager.GetString("SelectedOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in menu.
        /// </summary>
        public static string ShowInMenus {
            get {
                return ResourceManager.GetString("ShowInMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start publish.
        /// </summary>
        public static string StartPublish {
            get {
                return ResourceManager.GetString("StartPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this tag!.
        /// </summary>
        public static string TagsDelete {
            get {
                return ResourceManager.GetString("TagsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name is required!.
        /// </summary>
        public static string ValidationPageNameLength {
            get {
                return ResourceManager.GetString("ValidationPageNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Page Name field is required!.
        /// </summary>
        public static string ValidationPageNameRequired {
            get {
                return ResourceManager.GetString("ValidationPageNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start publish property is required!.
        /// </summary>
        public static string ValidationStartPublishRequired {
            get {
                return ResourceManager.GetString("ValidationStartPublishRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        public static string ViewDifferentVersions {
            get {
                return ResourceManager.GetString("ViewDifferentVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewPage {
            get {
                return ResourceManager.GetString("ViewPage", resourceCulture);
            }
        }
    }
}
