//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS_i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BackendResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackendResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS_i18n.BackendResources", typeof(BackendResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow comments.
        /// </summary>
        public static string AllowComments {
            get {
                return ResourceManager.GetString("AllowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Heading.
        /// </summary>
        public static string ArticleHeading {
            get {
                return ResourceManager.GetString("ArticleHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string ArticleIntro {
            get {
                return ResourceManager.GetString("ArticleIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string ByPrompt {
            get {
                return ResourceManager.GetString("ByPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Site!.
        /// </summary>
        public static string ConfigureMenu {
            get {
                return ResourceManager.GetString("ConfigureMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Header.
        /// </summary>
        public static string ContainerHeading {
            get {
                return ResourceManager.GetString("ContainerHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DashboardDeleteCurrent {
            get {
                return ResourceManager.GetString("DashboardDeleteCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DashboardEditCurrent {
            get {
                return ResourceManager.GetString("DashboardEditCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group and structurize your content. You can drag and drop items into topics..
        /// </summary>
        public static string DashboardGroupsDescription {
            get {
                return ResourceManager.GetString("DashboardGroupsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        public static string DashboardGroupsHeader {
            get {
                return ResourceManager.GetString("DashboardGroupsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your content.
        /// </summary>
        public static string DashBoardHeader {
            get {
                return ResourceManager.GetString("DashBoardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string DashboardStatusFilterAll {
            get {
                return ResourceManager.GetString("DashboardStatusFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts.
        /// </summary>
        public static string DashboardStatusFilterDrafts {
            get {
                return ResourceManager.GetString("DashboardStatusFilterDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string DashboardStatusFilterLabel {
            get {
                return ResourceManager.GetString("DashboardStatusFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string DashboardStatusFilterPublished {
            get {
                return ResourceManager.GetString("DashboardStatusFilterPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find documents.
        /// </summary>
        public static string DashboardTextFilterLabel {
            get {
                return ResourceManager.GetString("DashboardTextFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string DashboardViewCurrent {
            get {
                return ResourceManager.GetString("DashboardViewCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string DatePrompt {
            get {
                return ResourceManager.GetString("DatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeletePage {
            get {
                return ResourceManager.GetString("DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discus Javascript.
        /// </summary>
        public static string DisqusConfigScript {
            get {
                return ResourceManager.GetString("DisqusConfigScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your document was successfully saved!.
        /// </summary>
        public static string DocumentSaved {
            get {
                return ResourceManager.GetString("DocumentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Publish.
        /// </summary>
        public static string EndPublish {
            get {
                return ResourceManager.GetString("EndPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string FacebookConfigApiKey {
            get {
                return ResourceManager.GetString("FacebookConfigApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Secret.
        /// </summary>
        public static string FacebookConfigApiSecret {
            get {
                return ResourceManager.GetString("FacebookConfigApiSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type.
        /// </summary>
        public static string FileDocumentContentType {
            get {
                return ResourceManager.GetString("FileDocumentContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string FileDocumentFileName {
            get {
                return ResourceManager.GetString("FileDocumentFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string FileManagerEditFileApply {
            get {
                return ResourceManager.GetString("FileManagerEditFileApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files was successfully deleted.
        /// </summary>
        public static string FileManagerFilesWasDeleted {
            get {
                return ResourceManager.GetString("FileManagerFilesWasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by type.
        /// </summary>
        public static string FileManagerFilterByExtension {
            get {
                return ResourceManager.GetString("FileManagerFilterByExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by file name.
        /// </summary>
        public static string FileManagerFilterByFreeText {
            get {
                return ResourceManager.GetString("FileManagerFilterByFreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Images.
        /// </summary>
        public static string FileManagerLaunch {
            get {
                return ResourceManager.GetString("FileManagerLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the maximum number of images attached to this page..
        /// </summary>
        public static string FileManagerNoMoreFilesAllowed {
            get {
                return ResourceManager.GetString("FileManagerNoMoreFilesAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag files to the panel or click the upload button.
        /// </summary>
        public static string FileManagerTopTips {
            get {
                return ResourceManager.GetString("FileManagerTopTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file.
        /// </summary>
        public static string FileManagerUploadedDescription {
            get {
                return ResourceManager.GetString("FileManagerUploadedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a new file.
        /// </summary>
        public static string FileManagerUploadNew {
            get {
                return ResourceManager.GetString("FileManagerUploadNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FilePickerSaveSelected {
            get {
                return ResourceManager.GetString("FilePickerSaveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Files.
        /// </summary>
        public static string FilesMenu {
            get {
                return ResourceManager.GetString("FilesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click or drag and drop files to this pane..
        /// </summary>
        public static string FileUploadButtonText {
            get {
                return ResourceManager.GetString("FileUploadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Effect.
        /// </summary>
        public static string ImageApplyEffect {
            get {
                return ResourceManager.GetString("ImageApplyEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale.
        /// </summary>
        public static string ImageApplyGrayscale {
            get {
                return ResourceManager.GetString("ImageApplyGrayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string ImageApplyRotate {
            get {
                return ResourceManager.GetString("ImageApplyRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepia.
        /// </summary>
        public static string ImageApplySepia {
            get {
                return ResourceManager.GetString("ImageApplySepia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Serie.
        /// </summary>
        public static string ImageCarousel {
            get {
                return ResourceManager.GetString("ImageCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What now ?.
        /// </summary>
        public static string LeftMenuWelcome {
            get {
                return ResourceManager.GetString("LeftMenuWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing a page would be a good start, or maybe define a new document type....
        /// </summary>
        public static string LeftMenuWelcomeText {
            get {
                return ResourceManager.GetString("LeftMenuWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Types.
        /// </summary>
        public static string MenuConfigPageTypes {
            get {
                return ResourceManager.GetString("MenuConfigPageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string MenuConfigure {
            get {
                return ResourceManager.GetString("MenuConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string MenuConfigureSocial {
            get {
                return ResourceManager.GetString("MenuConfigureSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MenuDashBoard {
            get {
                return ResourceManager.GetString("MenuDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string MenuFiles {
            get {
                return ResourceManager.GetString("MenuFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Files.
        /// </summary>
        public static string MenuMyFiles {
            get {
                return ResourceManager.GetString("MenuMyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string MenuPublishNew {
            get {
                return ResourceManager.GetString("MenuPublishNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string MenuSecurity {
            get {
                return ResourceManager.GetString("MenuSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string MenuSecurityRoles {
            get {
                return ResourceManager.GetString("MenuSecurityRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MenuSecurityUsers {
            get {
                return ResourceManager.GetString("MenuSecurityUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string MenuUploadFiles {
            get {
                return ResourceManager.GetString("MenuUploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no revisions saved for this document yet!.
        /// </summary>
        public static string NoRevisions {
            get {
                return ResourceManager.GetString("NoRevisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to save this document before you can add files / images..
        /// </summary>
        public static string NoUpload {
            get {
                return ResourceManager.GetString("NoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes!.
        /// </summary>
        public static string PageConfirmDelete {
            get {
                return ResourceManager.GetString("PageConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? All selected files will be deleted!.
        /// </summary>
        public static string PageConfirmDeleteSure {
            get {
                return ResourceManager.GetString("PageConfirmDeleteSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string PageCreatedBy {
            get {
                return ResourceManager.GetString("PageCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string PageCreatedDate {
            get {
                return ResourceManager.GetString("PageCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Content.
        /// </summary>
        public static string PageDefaultEditor {
            get {
                return ResourceManager.GetString("PageDefaultEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string PageID {
            get {
                return ResourceManager.GetString("PageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string PageImageListRemoveImage {
            get {
                return ResourceManager.GetString("PageImageListRemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified by.
        /// </summary>
        public static string PageLastModifiedBy {
            get {
                return ResourceManager.GetString("PageLastModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        public static string PageLastModifiedDate {
            get {
                return ResourceManager.GetString("PageLastModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you requested is not available. It has either expired or is not yet published..
        /// </summary>
        public static string PageNotPublished {
            get {
                return ResourceManager.GetString("PageNotPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string PagePermissions {
            get {
                return ResourceManager.GetString("PagePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PageStatus {
            get {
                return ResourceManager.GetString("PageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string PageTypeDisplayArticle {
            get {
                return ResourceManager.GetString("PageTypeDisplayArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string PageTypeDisplayContainer {
            get {
                return ResourceManager.GetString("PageTypeDisplayContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url-Slug.
        /// </summary>
        public static string PageUrlSlug {
            get {
                return ResourceManager.GetString("PageUrlSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string PermissionSetAdmin {
            get {
                return ResourceManager.GetString("PermissionSetAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevated.
        /// </summary>
        public static string PermissionSetElevated {
            get {
                return ResourceManager.GetString("PermissionSetElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PermissionSetNone {
            get {
                return ResourceManager.GetString("PermissionSetNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish New!.
        /// </summary>
        public static string PublishNew {
            get {
                return ResourceManager.GetString("PublishNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide this.
        /// </summary>
        public static string RevisionHide {
            get {
                return ResourceManager.GetString("RevisionHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string RevisionLastMod {
            get {
                return ResourceManager.GetString("RevisionLastMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string RevisionSize {
            get {
                return ResourceManager.GetString("RevisionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RevisionStatus {
            get {
                return ResourceManager.GetString("RevisionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this revision.
        /// </summary>
        public static string RevisionUseThis {
            get {
                return ResourceManager.GetString("RevisionUseThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Revision.
        /// </summary>
        public static string RevisionViewThis {
            get {
                return ResourceManager.GetString("RevisionViewThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Draft.
        /// </summary>
        public static string SaveDraftPage {
            get {
                return ResourceManager.GetString("SaveDraftPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SavePage {
            get {
                return ResourceManager.GetString("SavePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Publish.
        /// </summary>
        public static string SavePublishPage {
            get {
                return ResourceManager.GetString("SavePublishPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveSiteDescriptionSettings {
            get {
                return ResourceManager.GetString("SaveSiteDescriptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveSocialMediaSettings {
            get {
                return ResourceManager.GetString("SaveSocialMediaSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/Off.
        /// </summary>
        public static string SelectedOrNot {
            get {
                return ResourceManager.GetString("SelectedOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in menu.
        /// </summary>
        public static string ShowInMenus {
            get {
                return ResourceManager.GetString("ShowInMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your website.
        /// </summary>
        public static string SiteDescriptionMediaSettingsHeader {
            get {
                return ResourceManager.GetString("SiteDescriptionMediaSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entitle, describe and upload a logo..
        /// </summary>
        public static string SiteDescriptionMediaSettingsHeaderDescription {
            get {
                return ResourceManager.GetString("SiteDescriptionMediaSettingsHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site description.
        /// </summary>
        public static string SiteDescriptionSiteDescription {
            get {
                return ResourceManager.GetString("SiteDescriptionSiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string SiteDescriptionSiteLogo {
            get {
                return ResourceManager.GetString("SiteDescriptionSiteLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site title.
        /// </summary>
        public static string SiteDescriptionSiteTitle {
            get {
                return ResourceManager.GetString("SiteDescriptionSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string SocialMediaActiveLabel {
            get {
                return ResourceManager.GetString("SocialMediaActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media Settings.
        /// </summary>
        public static string SocialMediaSettingsHeader {
            get {
                return ResourceManager.GetString("SocialMediaSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a social media is activated, a user will be able to write comments on your article by logging in to the social media service. Configuration at the social media developer site is required..
        /// </summary>
        public static string SocialMediaSettingsHeaderDescription {
            get {
                return ResourceManager.GetString("SocialMediaSettingsHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Publish.
        /// </summary>
        public static string StartPublish {
            get {
                return ResourceManager.GetString("StartPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this tag!.
        /// </summary>
        public static string TagsDelete {
            get {
                return ResourceManager.GetString("TagsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string TopicID {
            get {
                return ResourceManager.GetString("TopicID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string TopicNewColor {
            get {
                return ResourceManager.GetString("TopicNewColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TopicNewDescriptionLable {
            get {
                return ResourceManager.GetString("TopicNewDescriptionLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new topic!.
        /// </summary>
        public static string TopicNewSubmitButton {
            get {
                return ResourceManager.GetString("TopicNewSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &amp; Color.
        /// </summary>
        public static string TopicNewTitleLable {
            get {
                return ResourceManager.GetString("TopicNewTitleLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current topics.
        /// </summary>
        public static string TopicsHeaderCurrent {
            get {
                return ResourceManager.GetString("TopicsHeaderCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define a new topic.
        /// </summary>
        public static string TopicsHeaderNew {
            get {
                return ResourceManager.GetString("TopicsHeaderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in menu.
        /// </summary>
        public static string TopicShowInMenu {
            get {
                return ResourceManager.GetString("TopicShowInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None selected.
        /// </summary>
        public static string TopicsNoneSelected {
            get {
                return ResourceManager.GetString("TopicsNoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        public static string TopicsSettingsHeader {
            get {
                return ResourceManager.GetString("TopicsSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define your topics to better organize your content..
        /// </summary>
        public static string TopicsSettingsHeaderDescription {
            get {
                return ResourceManager.GetString("TopicsSettingsHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Key.
        /// </summary>
        public static string TwitterConfigConsumerKey {
            get {
                return ResourceManager.GetString("TwitterConfigConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Secret.
        /// </summary>
        public static string TwitterConfigConsumerSecret {
            get {
                return ResourceManager.GetString("TwitterConfigConsumerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Secret.
        /// </summary>
        public static string TwitterConfigTokenSecret {
            get {
                return ResourceManager.GetString("TwitterConfigTokenSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        public static string UnknownPublisher {
            get {
                return ResourceManager.GetString("UnknownPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid date.
        /// </summary>
        public static string ValidationPageDateTime {
            get {
                return ResourceManager.GetString("ValidationPageDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed: letters, numbers, spaces, dashes.
        /// </summary>
        public static string ValidationPageNameAllowedChars {
            get {
                return ResourceManager.GetString("ValidationPageNameAllowedChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name is required!.
        /// </summary>
        public static string ValidationPageNameLength {
            get {
                return ResourceManager.GetString("ValidationPageNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Page Name field is required!.
        /// </summary>
        public static string ValidationPageNameRequired {
            get {
                return ResourceManager.GetString("ValidationPageNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        public static string ValidationPagePropertyRequired {
            get {
                return ResourceManager.GetString("ValidationPagePropertyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be between {0} and {1} characters in length.
        /// </summary>
        public static string ValidationPagePropertyRequiredAndLength {
            get {
                return ResourceManager.GetString("ValidationPagePropertyRequiredAndLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start publish property is required!.
        /// </summary>
        public static string ValidationStartPublishRequired {
            get {
                return ResourceManager.GetString("ValidationStartPublishRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        public static string ViewDifferentVersions {
            get {
                return ResourceManager.GetString("ViewDifferentVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewPage {
            get {
                return ResourceManager.GetString("ViewPage", resourceCulture);
            }
        }
    }
}
